import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient, Role, Difficulty, QuestionVisibility } from './generated/prisma/client.js'
import bcrypt from 'bcrypt'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

async function main() {
  // Start fresh: delete all existing questions (idempotent)
  await prisma.question.deleteMany()
  console.log('Existing questions deleted.')

  // Delete old test users no longer in the set
  await prisma.user.deleteMany({ where: { email: { in: ['admin@quizztine.app', 'quizmaster@quizztine.app'] } } })

  // Seed test users (login:password)
  const user = await prisma.user.upsert({
    where: { email: 'user@quizztine.app' },
    update: { pseudo: 'user', password: await bcrypt.hash('user', 12), role: Role.USER, emailVerified: true },
    create: { pseudo: 'user', email: 'user@quizztine.app', password: await bcrypt.hash('user', 12), role: Role.USER, emailVerified: true },
  })
  const master1 = await prisma.user.upsert({
    where: { email: 'master1@quizztine.app' },
    update: { pseudo: 'master1', password: await bcrypt.hash('master1', 12), role: Role.QUIZMASTER, emailVerified: true },
    create: { pseudo: 'master1', email: 'master1@quizztine.app', password: await bcrypt.hash('master1', 12), role: Role.QUIZMASTER, emailVerified: true },
  })
  const master2 = await prisma.user.upsert({
    where: { email: 'master2@quizztine.app' },
    update: { pseudo: 'master2', password: await bcrypt.hash('master2', 12), role: Role.QUIZMASTER, emailVerified: true },
    create: { pseudo: 'master2', email: 'master2@quizztine.app', password: await bcrypt.hash('master2', 12), role: Role.QUIZMASTER, emailVerified: true },
  })
  const admin1 = await prisma.user.upsert({
    where: { email: 'admin1@quizztine.app' },
    update: { pseudo: 'admin1', password: await bcrypt.hash('admin1', 12), role: Role.QUIZADMIN, emailVerified: true },
    create: { pseudo: 'admin1', email: 'admin1@quizztine.app', password: await bcrypt.hash('admin1', 12), role: Role.QUIZADMIN, emailVerified: true },
  })
  const admin2 = await prisma.user.upsert({
    where: { email: 'admin2@quizztine.app' },
    update: { pseudo: 'admin2', password: await bcrypt.hash('admin2', 12), role: Role.QUIZADMIN, emailVerified: true },
    create: { pseudo: 'admin2', email: 'admin2@quizztine.app', password: await bcrypt.hash('admin2', 12), role: Role.QUIZADMIN, emailVerified: true },
  })
  console.log(`Users created: user/master1/master2/admin1/admin2`)

  // Seed default categories
  const defaultCategories = ['Geography', 'History', 'Science', 'Technology', 'Sports', 'Arts', 'Literature']
  for (const name of defaultCategories) {
    await prisma.category.upsert({
      where: { name },
      update: {},
      create: { name },
    })
  }
  console.log(`${defaultCategories.length} categories created (upsert).`)

  // Questions en français (seedKey stable pour upsert idempotent)
  const questions = [
    // ─── Géographie ───
    { seedKey: 'geo-capitale-france', text: 'Quelle est la capitale de la France ?', choices: [{ text: 'Londres', isCorrect: false }, { text: 'Paris', isCorrect: true }, { text: 'Berlin', isCorrect: false }, { text: 'Madrid', isCorrect: false }], explanation: 'Paris est la capitale de la France depuis le Xe siècle.', category: 'Geography', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'geo-plus-long-fleuve', text: 'Quel est le plus long fleuve du monde ?', choices: [{ text: 'Amazone', isCorrect: false }, { text: 'Nil', isCorrect: true }, { text: 'Mississippi', isCorrect: false }, { text: 'Yangzi Jiang', isCorrect: false }], explanation: 'Le Nil est traditionnellement considéré comme le plus long fleuve, avec environ 6 650 km.', category: 'Geography', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'geo-plus-grand-ocean', text: 'Quel est le plus grand océan du monde ?', choices: [{ text: 'Atlantique', isCorrect: false }, { text: 'Indien', isCorrect: false }, { text: 'Pacifique', isCorrect: true }, { text: 'Arctique', isCorrect: false }], explanation: "L'océan Pacifique est le plus grand et le plus profond, couvrant environ 165 millions de km².", category: 'Geography', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'geo-plus-haut-mont', text: "Quel est le plus haut sommet du monde ?", choices: [{ text: 'K2', isCorrect: false }, { text: "Mont Everest", isCorrect: true }, { text: 'Kangchenjunga', isCorrect: false }, { text: 'Lhotse', isCorrect: false }], explanation: "L'Everest culmine à 8 849 mètres d'altitude.", category: 'Geography', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'geo-desert-plus-grand', text: "Quel est le plus grand désert chaud du monde ?", choices: [{ text: 'Gobi', isCorrect: false }, { text: 'Kalahari', isCorrect: false }, { text: 'Sahara', isCorrect: true }, { text: 'Arabique', isCorrect: false }], explanation: "Le Sahara s'étend sur environ 9,2 millions de km² en Afrique du Nord.", category: 'Geography', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'geo-pays-plus-peuple', text: "Quel est le pays le plus peuplé du monde ?", choices: [{ text: 'États-Unis', isCorrect: false }, { text: 'Chine', isCorrect: false }, { text: 'Inde', isCorrect: true }, { text: 'Indonésie', isCorrect: false }], explanation: "L'Inde a dépassé la Chine en 2023 pour devenir le pays le plus peuplé avec plus de 1,4 milliard d'habitants.", category: 'Geography', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'geo-capitale-australie', text: "Quelle est la capitale de l'Australie ?", choices: [{ text: 'Sydney', isCorrect: false }, { text: 'Melbourne', isCorrect: false }, { text: 'Canberra', isCorrect: true }, { text: 'Brisbane', isCorrect: false }], explanation: "Canberra est la capitale de l'Australie depuis 1913.", category: 'Geography', difficulty: Difficulty.HARD, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'geo-detroit-magellan', text: "Quel détroit sépare l'Europe de l'Afrique ?", choices: [{ text: 'Détroit de Gibraltar', isCorrect: true }, { text: 'Détroit de Magellan', isCorrect: false }, { text: 'Détroit de Béring', isCorrect: false }, { text: "Détroit d'Ormuz", isCorrect: false }], explanation: "Le détroit de Gibraltar sépare l'Espagne du Maroc, reliant la Méditerranée à l'Atlantique.", category: 'Geography', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    // ─── Histoire ───
    { seedKey: 'hist-prise-bastille', text: "En quelle année a eu lieu la prise de la Bastille ?", choices: [{ text: '1787', isCorrect: false }, { text: '1789', isCorrect: true }, { text: '1791', isCorrect: false }, { text: '1793', isCorrect: false }], explanation: "La prise de la Bastille le 14 juillet 1789 marque le début de la Révolution française.", category: 'History', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'hist-premier-homme-lune', text: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", choices: [{ text: '1965', isCorrect: false }, { text: '1967', isCorrect: false }, { text: '1969', isCorrect: true }, { text: '1971', isCorrect: false }], explanation: "Apollo 11 a aluni le 20 juillet 1969 avec Neil Armstrong et Buzz Aldrin.", category: 'History', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'hist-fin-seconde-guerre', text: "En quelle année s'est terminée la Seconde Guerre mondiale ?", choices: [{ text: '1943', isCorrect: false }, { text: '1944', isCorrect: false }, { text: '1945', isCorrect: true }, { text: '1946', isCorrect: false }], explanation: "La Seconde Guerre mondiale s'est achevée en 1945 avec la capitulation de l'Allemagne en mai et du Japon en septembre.", category: 'History', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'hist-chute-mur-berlin', text: "En quelle année le mur de Berlin est-il tombé ?", choices: [{ text: '1987', isCorrect: false }, { text: '1989', isCorrect: true }, { text: '1991', isCorrect: false }, { text: '1993', isCorrect: false }], explanation: "Le mur de Berlin est tombé le 9 novembre 1989, marquant la fin de la guerre froide.", category: 'History', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'hist-roi-soleil', text: "Quel roi est connu comme le Roi-Soleil ?", choices: [{ text: 'Henri IV', isCorrect: false }, { text: 'Louis XIII', isCorrect: false }, { text: 'Louis XIV', isCorrect: true }, { text: 'Louis XV', isCorrect: false }], explanation: "Louis XIV, qui a régné de 1643 à 1715, est surnommé le Roi-Soleil.", category: 'History', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'hist-premiere-republique', text: "En quelle année la Première République française a-t-elle été proclamée ?", choices: [{ text: '1789', isCorrect: false }, { text: '1792', isCorrect: true }, { text: '1799', isCorrect: false }, { text: '1804', isCorrect: false }], explanation: "La Première République a été proclamée le 21 septembre 1792.", category: 'History', difficulty: Difficulty.HARD, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'hist-traite-versailles', text: "Quel traité a mis fin à la Première Guerre mondiale ?", choices: [{ text: 'Traité de Versailles', isCorrect: true }, { text: "Traité de Paris", isCorrect: false }, { text: "Traité de Vienne", isCorrect: false }, { text: "Traité de Madrid", isCorrect: false }], explanation: "Le traité de Versailles a été signé le 28 juin 1919.", category: 'History', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'hist-empire-romain', text: "Quel empire a été dirigé par Jules César ?", choices: [{ text: 'Empire grec', isCorrect: false }, { text: 'Empire romain', isCorrect: true }, { text: 'Empire perse', isCorrect: false }, { text: 'Empire byzantin', isCorrect: false }], explanation: "Jules César a été un général et dictateur de la République romaine, posant les bases de l'Empire romain.", category: 'History', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    // ─── Sciences ───
    { seedKey: 'sci-centrale-cellule', text: "Qu'est-ce que la 'centrale énergétique' de la cellule ?", choices: [{ text: 'Noyau', isCorrect: false }, { text: 'Mitochondrie', isCorrect: true }, { text: 'Ribosome', isCorrect: false }, { text: 'Appareil de Golgi', isCorrect: false }], explanation: "Les mitochondries sont surnommées la centrale énergétique car elles produisent l'ATP.", category: 'Science', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sci-planete-rouge', text: "Pourquoi Mars est-elle appelée la planète rouge ?", choices: [{ text: "Elle est couverte de fleurs rouges", isCorrect: false }, { text: "Son sol est riche en oxyde de fer", isCorrect: true }, { text: "Elle a une atmosphère rouge", isCorrect: false }, { text: "Elle réfléchit la lumière d'une étoile rouge", isCorrect: false }], explanation: "Mars apparaît rouge car sa surface contient de l'oxyde de fer (rouille).", category: 'Science', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sci-nombre-os', text: "Combien d'os compte le corps humain adulte ?", choices: [{ text: '106', isCorrect: false }, { text: '206', isCorrect: true }, { text: '306', isCorrect: false }, { text: '406', isCorrect: false }], explanation: "Un adulte possède 206 os. Les bébés en naissent avec environ 270 qui fusionnent.", category: 'Science', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sci-eau-corps', text: "Quel pourcentage du corps humain est constitué d'eau ?", choices: [{ text: '40 %', isCorrect: false }, { text: '60 %', isCorrect: true }, { text: '80 %', isCorrect: false }, { text: '90 %', isCorrect: false }], explanation: "Le corps humain est composé d'environ 60 % d'eau.", category: 'Science', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sci-nombres-premiers', text: "Lesquels de ces nombres sont premiers ? (plusieurs choix)", choices: [{ text: '17', isCorrect: true }, { text: '21', isCorrect: false }, { text: '29', isCorrect: true }, { text: '33', isCorrect: false }], explanation: "17 et 29 sont premiers. 21 = 3×7, 33 = 3×11.", category: 'Science', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sci-photosynthese', text: "Quel gaz les plantes absorbent-elles lors de la photosynthèse ?", choices: [{ text: 'Oxygène', isCorrect: false }, { text: 'Azote', isCorrect: false }, { text: 'Dioxyde de carbone', isCorrect: true }, { text: 'Hydrogène', isCorrect: false }], explanation: "Les plantes absorbent le CO₂ et rejettent de l'oxygène pendant la photosynthèse.", category: 'Science', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sci-vitesse-lumiere', text: "Quelle est la vitesse approximative de la lumière dans le vide ?", choices: [{ text: '300 000 km/s', isCorrect: true }, { text: '150 000 km/s', isCorrect: false }, { text: '500 000 km/s', isCorrect: false }, { text: '1 000 000 km/s', isCorrect: false }], explanation: "La lumière se déplace à environ 299 792 km/s dans le vide.", category: 'Science', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sci-atome-noyau', text: "De quoi est composé le noyau d'un atome ?", choices: [{ text: 'Protons et neutrons', isCorrect: true }, { text: 'Électrons et protons', isCorrect: false }, { text: 'Neutrons et électrons', isCorrect: false }, { text: 'Protons seulement', isCorrect: false }], explanation: "Le noyau atomique contient des protons (chargés +) et des neutrons (neutres).", category: 'Science', difficulty: Difficulty.HARD, visibility: QuestionVisibility.PUBLIC },
    // ─── Technologie ───
    { seedKey: 'tech-sigle-cpu', text: "Que signifie le sigle CPU ?", choices: [{ text: 'Central Programming Unit', isCorrect: false }, { text: 'Central Processing Unit', isCorrect: true }, { text: 'Computer Personal Unit', isCorrect: false }, { text: 'Core Processing Unit', isCorrect: false }], explanation: "CPU signifie Central Processing Unit, le composant principal qui exécute les instructions.", category: 'Technology', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'tech-http-404', text: "Que signifie le code HTTP 404 ?", choices: [{ text: 'Erreur interne du serveur', isCorrect: false }, { text: 'Interdit', isCorrect: false }, { text: 'Introuvable', isCorrect: true }, { text: 'Non autorisé', isCorrect: false }], explanation: "HTTP 404 signifie que la ressource demandée est introuvable sur le serveur.", category: 'Technology', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'tech-langages-programmation', text: "Lesquels de ces langages sont des langages de programmation ? (plusieurs choix)", choices: [{ text: 'Python', isCorrect: true }, { text: 'HTML', isCorrect: false }, { text: 'TypeScript', isCorrect: true }, { text: 'CSS', isCorrect: false }], explanation: "Python et TypeScript sont des langages de programmation. HTML et CSS sont des langages de balisage/style.", category: 'Technology', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'tech-sql-join', text: "Quelle clause SQL permet de combiner des lignes de plusieurs tables ?", choices: [{ text: 'MERGE', isCorrect: false }, { text: 'UNION', isCorrect: false }, { text: 'JOIN', isCorrect: true }, { text: 'COMBINE', isCorrect: false }], explanation: "JOIN combine les lignes de deux tables ou plus basées sur une colonne commune.", category: 'Technology', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'tech-json', text: "Que signifie le sigle JSON ?", choices: [{ text: 'Java Standard Object Notation', isCorrect: false }, { text: 'JavaScript Object Notation', isCorrect: true }, { text: 'Java Serialized Object Network', isCorrect: false }, { text: 'JavaScript Online Notation', isCorrect: false }], explanation: "JSON signifie JavaScript Object Notation, un format léger d'échange de données.", category: 'Technology', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'tech-https', text: "Que signifie le S dans HTTPS ?", choices: [{ text: 'Secure', isCorrect: true }, { text: 'Standard', isCorrect: false }, { text: 'Server', isCorrect: false }, { text: 'Simple', isCorrect: false }], explanation: "HTTPS = HTTP + Secure (sécurisé via TLS/SSL).", category: 'Technology', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'tech-algorithme', text: "Qu'est-ce qu'un algorithme ?", choices: [{ text: 'Un langage de programmation', isCorrect: false }, { text: "Une séquence d'instructions pour résoudre un problème", isCorrect: true }, { text: 'Un composant électronique', isCorrect: false }, { text: 'Un type de base de données', isCorrect: false }], explanation: "Un algorithme est une suite finie d'opérations permettant de résoudre un problème.", category: 'Technology', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'tech-cloud', text: "Que signifie le terme 'cloud computing' ?", choices: [{ text: 'Calculs météorologiques', isCorrect: false }, { text: "Fourniture de services informatiques via Internet", isCorrect: true }, { text: 'Stockage sur disque dur local', isCorrect: false }, { text: "Réseau d'ordinateurs physiques", isCorrect: false }], explanation: "Le cloud computing permet d'accéder à des ressources informatiques à la demande via Internet.", category: 'Technology', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    // ─── Littérature ───
    { seedKey: 'litr-mona-lisa', text: "Qui a peint la Joconde ?", choices: [{ text: 'Michel-Ange', isCorrect: false }, { text: 'Léonard de Vinci', isCorrect: true }, { text: 'Raphaël', isCorrect: false }, { text: 'Caravage', isCorrect: false }], explanation: "La Joconde a été peinte par Léonard de Vinci entre 1503 et 1519.", category: 'Literature', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'litr-ecrivain-miserables', text: "Qui a écrit 'Les Misérables' ?", choices: [{ text: 'Émile Zola', isCorrect: false }, { text: 'Victor Hugo', isCorrect: true }, { text: 'Gustave Flaubert', isCorrect: false }, { text: 'Alexandre Dumas', isCorrect: false }], explanation: "Victor Hugo a publié 'Les Misérables' en 1862.", category: 'Literature', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'litr-petit-prince', text: "Qui a écrit 'Le Petit Prince' ?", choices: [{ text: 'Antoine de Saint-Exupéry', isCorrect: true }, { text: 'Albert Camus', isCorrect: false }, { text: 'Marcel Proust', isCorrect: false }, { text: 'Jean-Paul Sartre', isCorrect: false }], explanation: "Le Petit Prince a été écrit par Antoine de Saint-Exupéry en 1943.", category: 'Literature', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'litr-romans-shakespeare', text: "Combien de pièces Shakespeare a-t-il écrites ?", choices: [{ text: '27', isCorrect: false }, { text: '37', isCorrect: true }, { text: '47', isCorrect: false }, { text: '57', isCorrect: false }], explanation: "Shakespeare a écrit 37 pièces (39 en comptant les collaborations).", category: 'Literature', difficulty: Difficulty.HARD, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'litr-1984-auteur', text: "Qui a écrit le roman '1984' ?", choices: [{ text: 'Aldous Huxley', isCorrect: false }, { text: 'George Orwell', isCorrect: true }, { text: 'Ray Bradbury', isCorrect: false }, { text: 'H.G. Wells', isCorrect: false }], explanation: "George Orwell a publié '1984' en 1949.", category: 'Literature', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'litr-fables-fontaine', text: "Qui a écrit les Fables ?", choices: [{ text: 'Molière', isCorrect: false }, { text: 'Jean de La Fontaine', isCorrect: true }, { text: 'Racine', isCorrect: false }, { text: 'Boileau', isCorrect: false }], explanation: "Jean de La Fontaine a publié ses Fables entre 1668 et 1694.", category: 'Literature', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'litr-camus-peste', text: "Quel prix Nobel de littérature a écrit 'La Peste' ?", choices: [{ text: 'Jean-Paul Sartre', isCorrect: false }, { text: 'Albert Camus', isCorrect: true }, { text: 'Samuel Beckett', isCorrect: false }, { text: 'Ernest Hemingway', isCorrect: false }], explanation: "Albert Camus a publié 'La Peste' en 1947 et reçu le prix Nobel de littérature en 1957.", category: 'Literature', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'litr-verne-tour-monde', text: "Qui a écrit 'Le Tour du monde en 80 jours' ?", choices: [{ text: 'Jules Verne', isCorrect: true }, { text: 'Alexandre Dumas', isCorrect: false }, { text: 'Charles Dickens', isCorrect: false }, { text: 'H.G. Wells', isCorrect: false }], explanation: "Jules Verne a publié ce roman en 1872.", category: 'Literature', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    // ─── Sports ───
    { seedKey: 'sport-maillot-jaune', text: "De quelle couleur est le maillot du leader du Tour de France ?", choices: [{ text: 'Vert', isCorrect: false }, { text: 'À pois', isCorrect: false }, { text: 'Jaune', isCorrect: true }, { text: 'Blanc', isCorrect: false }], explanation: "Le leader du Tour de France porte le maillot jaune.", category: 'Sports', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sport-origine-jo', text: "Où sont nés les Jeux Olympiques antiques ?", choices: [{ text: 'Rome', isCorrect: false }, { text: 'Athènes', isCorrect: false }, { text: 'Olympie', isCorrect: true }, { text: 'Sparte', isCorrect: false }], explanation: "Les Jeux Olympiques antiques se déroulaient à Olympie, en Grèce, à partir de 776 av. J.-C.", category: 'Sports', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sport-coupe-monde-foot', text: "Quel pays a remporté la Coupe du monde de football en 2018 ?", choices: [{ text: 'Brésil', isCorrect: false }, { text: 'Allemagne', isCorrect: false }, { text: 'France', isCorrect: true }, { text: 'Argentine', isCorrect: false }], explanation: "La France a remporté la Coupe du monde 2018 en battant la Croatie 4-2.", category: 'Sports', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sport-tennis-rolan-garros', text: "Sur quelle surface se joue Roland-Garros ?", choices: [{ text: 'Gazon', isCorrect: false }, { text: 'Terre battue', isCorrect: true }, { text: 'Dur', isCorrect: false }, { text: 'Moquette', isCorrect: false }], explanation: "Roland-Garros est le tournoi du Grand Chelem sur terre battue.", category: 'Sports', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sport-record-100m', text: "Qui détient le record du monde du 100 mètres ?", choices: [{ text: 'Usain Bolt', isCorrect: true }, { text: 'Carl Lewis', isCorrect: false }, { text: 'Justin Gatlin', isCorrect: false }, { text: 'Asafa Powell', isCorrect: false }], explanation: "Usain Bolt détient le record du 100 m en 9,58 secondes, établi en 2009.", category: 'Sports', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sport-nba-titres', text: "Quelle équipe a le plus de titres NBA ?", choices: [{ text: 'Chicago Bulls', isCorrect: false }, { text: 'Boston Celtics', isCorrect: true }, { text: 'Los Angeles Lakers', isCorrect: false }, { text: 'Golden State Warriors', isCorrect: false }], explanation: "Les Celtics de Boston détiennent le record avec 18 titres NBA.", category: 'Sports', difficulty: Difficulty.HARD, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sport-jo-ete-hiver', text: "À quelle fréquence ont lieu les Jeux Olympiques ?", choices: [{ text: 'Tous les 2 ans', isCorrect: false }, { text: 'Tous les 4 ans', isCorrect: true }, { text: 'Tous les 3 ans', isCorrect: false }, { text: 'Tous les 5 ans', isCorrect: false }], explanation: "Les JO ont lieu tous les 4 ans, en alternance été/hiver tous les 2 ans.", category: 'Sports', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'sport-marathon-distance', text: "Quelle est la distance officielle d'un marathon ?", choices: [{ text: '40 km', isCorrect: false }, { text: '42,195 km', isCorrect: true }, { text: '45 km', isCorrect: false }, { text: '38 km', isCorrect: false }], explanation: "Le marathon fait 42,195 km, une distance standardisée depuis 1921.", category: 'Sports', difficulty: Difficulty.HARD, visibility: QuestionVisibility.PUBLIC },
    // ─── Arts ───
    { seedKey: 'art-peinture-cri', text: "Qui a peint 'Le Cri' ?", choices: [{ text: 'Vincent van Gogh', isCorrect: false }, { text: 'Edvard Munch', isCorrect: true }, { text: 'Pablo Picasso', isCorrect: false }, { text: 'Claude Monet', isCorrect: false }], explanation: "Le Cri a été peint par Edvard Munch en 1893.", category: 'Arts', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'art-musee-louvre', text: "Où se trouve le musée du Louvre ?", choices: [{ text: 'Londres', isCorrect: false }, { text: 'Paris', isCorrect: true }, { text: 'Rome', isCorrect: false }, { text: 'Madrid', isCorrect: false }], explanation: "Le musée du Louvre est situé à Paris, c'est le plus grand musée du monde.", category: 'Arts', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'art-instruments-cordes', text: "Lequel de ces instruments est à cordes ?", choices: [{ text: 'Flûte', isCorrect: false }, { text: 'Violon', isCorrect: true }, { text: 'Trompette', isCorrect: false }, { text: 'Batterie', isCorrect: false }], explanation: "Le violon est un instrument à cordes frottées.", category: 'Arts', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'art-mouvement-impressionnisme', text: "Quel peintre est considéré comme le père de l'impressionnisme ?", choices: [{ text: 'Claude Monet', isCorrect: true }, { text: 'Auguste Renoir', isCorrect: false }, { text: 'Edgar Degas', isCorrect: false }, { text: 'Paul Cézanne', isCorrect: false }], explanation: "Claude Monet est le chef de file de l'impressionnisme, avec 'Impression, soleil levant'.", category: 'Arts', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'art-beethoven-symphonies', text: "Combien de symphonies Beethoven a-t-il composées ?", choices: [{ text: '5', isCorrect: false }, { text: '7', isCorrect: false }, { text: '9', isCorrect: true }, { text: '11', isCorrect: false }], explanation: "Beethoven a composé 9 symphonies, dont la célèbre 9e avec 'Ode à la joie'.", category: 'Arts', difficulty: Difficulty.MEDIUM, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'art-style-archi-gothique', text: "Quel est l'exemple le plus connu d'architecture gothique en France ?", choices: [{ text: 'Notre-Dame de Paris', isCorrect: true }, { text: 'Le Louvre', isCorrect: false }, { text: 'La tour Eiffel', isCorrect: false }, { text: 'Le Château de Versailles', isCorrect: false }], explanation: "Notre-Dame de Paris est un chef-d'œuvre de l'architecture gothique française.", category: 'Arts', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'art-picasso-cubisme', text: "De quel mouvement artistique Pablo Picasso est-il un pionnier ?", choices: [{ text: 'Surréalisme', isCorrect: false }, { text: 'Cubisme', isCorrect: true }, { text: 'Expressionnisme', isCorrect: false }, { text: 'Pop art', isCorrect: false }], explanation: "Picasso a cofondé le cubisme avec Georges Braque au début du XXe siècle.", category: 'Arts', difficulty: Difficulty.HARD, visibility: QuestionVisibility.PUBLIC },
    { seedKey: 'art-cinema-fratelli-lumiere', text: "Qui a inventé le cinéma ?", choices: [{ text: 'Les frères Lumière', isCorrect: true }, { text: 'Thomas Edison', isCorrect: false }, { text: 'Georges Méliès', isCorrect: false }, { text: 'Charlie Chaplin', isCorrect: false }], explanation: "Les frères Auguste et Louis Lumière ont inventé le cinématographe en 1895.", category: 'Arts', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PUBLIC },
    // ─── Privée (quizmaster) ───
    { seedKey: 'private-2-plus-2', text: "Question privée : combien font 2+2 ?", choices: [{ text: '3', isCorrect: false }, { text: '4', isCorrect: true }, { text: '5', isCorrect: false }, { text: '22', isCorrect: false }], explanation: "2+2 = 4. Question réservée aux quizmasters et admins.", category: 'Science', difficulty: Difficulty.EASY, visibility: QuestionVisibility.PRIVATE, authorId: master1.id },
  ]

  for (const q of questions) {
    const { seedKey, ...rest } = q
    await prisma.question.upsert({
      where: { seedKey },
      update: {},
      create: { seedKey, ...rest },
    })
  }
  console.log(`${questions.length} questions created (upsert).`)

  console.log('\n--- Seed complete ---')
  console.log('user:    user@quizztine.app / user     (USER)')
  console.log('master1: master1@quizztine.app / master1 (QUIZMASTER)')
  console.log('master2: master2@quizztine.app / master2 (QUIZMASTER)')
  console.log('admin1:  admin1@quizztine.app / admin1  (QUIZADMIN)')
  console.log('admin2:  admin2@quizztine.app / admin2  (QUIZADMIN)')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
