FROM node:26-alpine
WORKDIR /app
COPY package.json index.html vite.config.ts tsconfig.json tsconfig.app.json tsconfig.node.json ./
RUN npm install --legacy-peer-deps
EXPOSE 5173
CMD ["npm", "run", "dev"]
